---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-clusterrole 
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding 
metadata:
  name: pod-watcher-clusterbinding 
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
    namespace: default
roleRef:
  kind: ClusterRole 
  name: pod-watcher-clusterrole 
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-watchdog-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-watchdog
  template:
    metadata:
      labels:
        app: k8s-watchdog
    spec:
      serviceAccountName: pod-watcher-sa
      containers:
        - name: watchdog-container
          image: k8s-watchdog:latest
          imagePullPolicy: Never 
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: k8s-watchdog-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-watchdog-config
  namespace: default
data:
  config.yaml: |
    watch: 
      resources:
        - pods
      namespaces: 
        - default
        - kube-system
    notifier:
      type: stdout
